### ISSUE TITLE
Simple Example: Get Button and use with a signal

### ISSUE THREAD

**Issue by pycebs** [mrccnt/gotk3-glade-example#2]
Let's take a simple example:

Glade: I have a simple button named "button_1 that has an on_click signal for let's say "on_click_dostuff".

How do I get "button_1" into my go code and how can I connect it to the function "on_click_dostuff"?

Sorry if this is too basic, but I am still very new to Go. Things are much easier in PyGPbject.

Also why is this Glade example so much different from yours:

https://gitlab.gnome.org/chergert/hello/commit/f225c51efec7f4c319120aa7e1c1e47e0c28bbfe

Is this a newer/older version?

**Comment by mrccnt** [comment]
Take a look at the listbox function. Getting a button from a glade file works exactly the same way.

Get the object from your builder and then assert that the object is of expected type. Then make use of the connect function to bind your signal to a given function.

My example here is different from the one you showed because the glade file here allready contains the GtkWindow object, while your example does not. The rest ist pretty much the same...

Sorry that I can not explain in full detail at the moment, but I am on holidays right now... ;)

**Comment by pycebs** [comment]
OK that worked. Thanks a lot!
